#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
relations_pilot.py -- companion to note II, Sections "Reading the relation" and
"Learning the correspondence between codes".

R1  A hierarchy (organisation chart): persons move k steps along a relation
    (up, down-left, down-right) through vacant positions. The relation is NOT supplied to
    the reader: three propagators, one per generator ("relational velocity"), are reset at
    the anchor (the vacated position) and run in parallel; the one whose state reaches the
    positive mismatch is kept. Staircase and ablations; the same events with the relation
    bound as an argument of the order.
R2  The guard of note I learned in the hierarchy: available extent H generated by the same
    propagation halted at the first occupied or missing position; signed comparison with the
    required extent; Beta evidence rule of note I (>= 5 observations and P(q > 0.9) > 0.95).
    Pooled comparator vs per-position comparator; test with unseen persons and an unseen
    length (k = 3).
R3  A branching relation: 'down' to either subordinate. Reading recovers relation, extent
    and the path of branches; execution of "down, k" needs the path as one more bound
    argument (a relative address).
R4  Correspondence between codes, on the line world of note II: the hand and the shelf use
    independent random codes for each colour; role binding uses a heteroassociation learned
    locally, one update per event, W <- W + d-_hand (d+_shelf)^T, plain (Hebbian) or with
    the outgoing weights of each presynaptic unit normalised to unit sum before they are
    used (outgoing-weight, or row, normalisation: each hand unit votes with the distribution
    of shelf units it has co-occurred with, so frequent fillers do not dominate rare ones).

Only NumPy (+ scipy.stats.beta for the evidence rule). Fixed seeds. Run from code/:
    python3 relations_pilot.py
"""
import json
import numpy as np
from scipy.stats import beta as beta_dist
import canon_spaces_pilot as cs

N, KC = cs.N, cs.KC
DEPTH, NPOS, KMAX = 4, 15, 4
REL = {"up": lambda i: (i - 1) // 2 if i > 0 else -1,
       "dl": lambda i: 2 * i + 1 if 2 * i + 1 < NPOS else -1,
       "dr": lambda i: 2 * i + 2 if 2 * i + 2 < NPOS else -1}

_rp = np.random.default_rng(11)
PERSON = np.zeros((17, N), dtype=int)                  # row 0 = vacancy
for p in range(1, 17):
    PERSON[p, _rp.choice(N, KC, replace=False)] = 1
TRAIN_P, TEST_P = list(range(1, 9)), list(range(9, 17))

def path(i, steps):
    """steps: list of relation names. Returns the positions visited (None if off the chart)."""
    out = []
    for v in steps:
        i = REL[v](i)
        if i < 0: return None
        out.append(i)
    return out

def attempt_ok(occ, p, steps):
    pp = path(p, steps)
    return pp is not None and all(occ[j] == 0 for j in pp)

# ------------------------------------------------------------------------------------------
# World: episodes of moves with probes (accepted / refused attempts) as in note I
# ------------------------------------------------------------------------------------------
def episodes(n_ep, people, ks, rng, branching=False, n_moves=10, n_probe=4):
    events, attempts = [], []
    for _ in range(n_ep):
        occ = np.zeros(NPOS, dtype=int)
        who = rng.choice(people, size=int(rng.integers(4, 8)), replace=False)
        occ[rng.choice(NPOS, size=len(who), replace=False)] = who
        for _ in range(n_moves):
            def sample():
                p = int(rng.choice(np.flatnonzero(occ)))
                k = int(rng.choice(ks))
                if branching:
                    v = str(rng.choice(["up", "down"]))
                    steps = ["up"] * k if v == "up" else [str(rng.choice(["dl", "dr"])) for _ in range(k)]
                else:
                    v = str(rng.choice(["up", "dl", "dr"])); steps = [v] * k
                return p, v, k, steps
            for _ in range(n_probe):
                p, v, k, steps = sample()
                attempts.append(dict(occ=occ.copy(), p=p, v=v, k=k, steps=steps, ok=attempt_ok(occ, p, steps)))
            for _ in range(50):
                p, v, k, steps = sample()
                if attempt_ok(occ, p, steps): break
            else:
                continue
            dest = path(p, steps)[-1]
            after = occ.copy(); after[dest] = occ[p]; after[p] = 0
            events.append(dict(before=occ.copy(), after=after, p=p, v=v, k=k, steps=steps, who=int(occ[p]), dest=dest))
            occ = after
    return events, attempts

# ------------------------------------------------------------------------------------------
# R1: reading the relation by propagators in competition
# ------------------------------------------------------------------------------------------
def read_event(ev, reset=True, conj=True, extent=True, relation_as_argument=False):
    S0, S1 = PERSON[ev["before"]], PERSON[ev["after"]]
    d = S1 - S0; dplus, dminus = (d > 0).astype(int), (d < 0).astype(int)
    a = int(np.argmax(dminus.sum(axis=1)))                     # anchor: the vacated position
    target = set(np.flatnonzero(dplus.sum(axis=1)))
    winners = []
    for v in ("up", "dl", "dr"):                               # three propagators in parallel
        i, r = a, 0
        while r < KMAX:
            i = REL[v](i); r += 1
            if i < 0: break
            if i in target: winners.append((v, r, i)); break
            if dplus[i].any() or dminus[i].any(): break        # a change that is not the target
    if len(winners) != 1:
        return ("unread",), None
    v, r, dest = winners[0]
    X = dplus[dest] @ dminus[a] >= KC - 1                      # coincidence: same person
    ext_ok = r == ev["k"]                                      # thermometer comparison with the order
    rel_ok = v == ev["v"]
    who = ("X",) if (conj and X) else (tuple(np.flatnonzero(dminus[a])),)
    where = () if reset else (a, dest)
    ext = () if extent and ext_ok else (r,)
    rel = ("arg",) if (relation_as_argument and rel_ok) else (v,)
    return ("MOVE",) + rel + who + where + ext, dict(v=v, r=r, dest=dest, X=bool(X))

# ------------------------------------------------------------------------------------------
# R2: learned guard
# ------------------------------------------------------------------------------------------
def comparator(at):
    """Available extent H (propagation halted at the first occupied or missing position),
    required extent W (thermometer of k), signed comparison per position and pooled,
    and irrelevant control signals."""
    occ, p, steps, k = at["occ"], at["p"], at["steps"], at["k"]
    H = np.zeros(KMAX, dtype=int); i = p
    rel_steps = steps + [steps[-1]] * (KMAX - len(steps)) if steps else []
    for j in range(KMAX):
        i = REL[rel_steps[j]](i) if i >= 0 else -1
        if i < 0 or occ[i] != 0: break
        H[j] = 1
    Wt = (np.arange(KMAX) < k).astype(int)
    nminus, nplus = Wt * (1 - H), H * (1 - Wt)
    pooled = {"N-": int(nminus.any()), "N+": int(nplus.any())}
    per = {f"C-{j + 1}": int(nminus[j]) for j in range(KMAX)}
    per.update({f"C+{j + 1}": int(nplus[j]) for j in range(KMAX)})
    irr = {"anchor index even": int(p % 2 == 0), "relation is up": int(steps[0] == "up"),
           "person code has unit 1": int(PERSON[occ[p]][0] == 1),
           "more than five persons": int((occ > 0).sum() > 5)}
    return pooled, per, irr

def learn_guard(attempts, variant):
    counts = {}
    for at in attempts:
        pooled, per, irr = comparator(at)
        units = dict(irr)
        units.update(pooled if variant == "pooled" else per)
        for u, on in units.items():
            if on:
                s, f = counts.get(u, (0, 0))
                counts[u] = (s + int(at["ok"]), f + int(not at["ok"]))
    selected = [u for u, (s, f) in counts.items()
                if s + f >= 5 and beta_dist.sf(0.9, 1 + f, 1 + s) > 0.95]
    return selected, counts

def guard(at, selected, variant):
    pooled, per, irr = comparator(at)
    units = dict(irr); units.update(pooled if variant == "pooled" else per)
    return not any(units.get(u, 0) for u in selected)

# ------------------------------------------------------------------------------------------
# R4: correspondence between codes
# ------------------------------------------------------------------------------------------
def correspondence(events, n_col, normalise, seed=13):
    rng = np.random.default_rng(seed)
    HAND = np.zeros((n_col + 1, N), dtype=int)
    for c in range(1, n_col + 1):
        HAND[c, rng.choice(N, KC, replace=False)] = 1
    W = np.zeros((N, N)); seen = set()
    out = dict(first=0, first_bound=0, later=0, later_bound=0, false_tests=0, false_bound=0, fail_occurrence=[])
    nseen = {}
    for ev in events:
        c = ev["c"]; h = HAND[c]
        ch = np.flatnonzero(ev["before"] != ev["after"])
        shelf = cs.CODE[ev["after"][ch[0]]]                        # d+ at a changed slot
        if normalise is True:                                      # outgoing weights of each presynaptic
            rs = W.sum(axis=1, keepdims=True)                      # unit normalised to unit sum
            Wn = np.divide(W, rs, out=np.zeros_like(W), where=rs > 0)
            pred = Wn.T @ h
        else:
            pred = W.T @ h
        top = np.zeros(N, dtype=int)
        if pred.max() > 0: top[np.argsort(pred)[-KC:]] = 1
        bound = top @ shelf >= KC - 1
        nseen[c] = nseen.get(c, 0) + 1
        if c in seen:
            out["later"] += 1; out["later_bound"] += int(bound)
            if not bound: out["fail_occurrence"].append(nseen[c])
        else: out["first"] += 1; out["first_bound"] += int(bound)
        if c in seen:                                              # a different colour appears
            c2 = int(rng.choice([x for x in range(1, n_col + 1) if x != c]))
            out["false_tests"] += 1; out["false_bound"] += int(top @ cs.CODE[c2] >= KC - 1)
        W += np.outer(h, shelf); seen.add(c)                       # one local update per event
        if normalise == "every_update":                            # control: renormalise W after each update
            rs = W.sum(axis=1, keepdims=True); W = np.divide(W, rs, out=np.zeros_like(W), where=rs > 0)
    return out

# ------------------------------------------------------------------------------------------
if __name__ == "__main__":
    res = {}
    print("R1. A HIERARCHY: reading the relation by three propagators in parallel")
    ev_tr, at_tr = episodes(1200, TRAIN_P, (1, 2), np.random.default_rng(31))
    raw = len(set((tuple(e["before"]), tuple(e["after"])) for e in ev_tr))
    reads = [read_event(e) for e in ev_tr]
    correct = sum(inf is not None and inf["v"] == e["v"] and inf["r"] == e["k"] and inf["X"]
                  for e, (p, inf) in zip(ev_tr, reads))
    full = [p for p, _ in reads]
    from collections import Counter
    per_rel = Counter(p[1] for p in full)
    r1 = dict(moves=len(ev_tr), raw=raw, full=len(set(full)), per_relation=dict(per_rel),
              read_correctly=correct,
              no_reset=len(set(read_event(e, reset=False)[0] for e in ev_tr)),
              no_conjunction=len(set(read_event(e, conj=False)[0] for e in ev_tr)),
              no_extent=len(set(read_event(e, extent=False)[0] for e in ev_tr)),
              relation_as_argument=len(set(read_event(e, relation_as_argument=True)[0] for e in ev_tr)))
    res["R1"] = r1
    print(f"   {r1['moves']} accepted moves ({r1['raw']} distinct raw transitions); relation, extent and X read "
          f"correctly in {correct}; patterns: full {r1['full']} {dict(per_rel)}; no reset {r1['no_reset']}; "
          f"no conjunction {r1['no_conjunction']}; no extent comparison {r1['no_extent']}; "
          f"relation bound as argument of the order {r1['relation_as_argument']}")

    print("\nR2. THE GUARD OF NOTE I, LEARNED IN THE HIERARCHY")
    _, at_te = episodes(800, TEST_P, (1, 2, 3), np.random.default_rng(37))
    r2 = dict(train_attempts=len(at_tr), train_accepted=sum(a["ok"] for a in at_tr), test_attempts=len(at_te))
    for variant in ("pooled", "per_position"):
        sel, counts = learn_guard(at_tr, variant)
        errs = [(guard(a, sel, variant) != a["ok"], a["k"]) for a in at_te]
        r2[variant] = dict(selected=sel, counts={u: list(v) for u, v in counts.items()},
                           errors=sum(e for e, _ in errs),
                           errors_by_k={k: sum(e for e, kk in errs if kk == k) for k in (1, 2, 3)},
                           tests_by_k={k: sum(1 for _, kk in errs if kk == k) for k in (1, 2, 3)})
        print(f"   {variant:12s}: selected {sel}; test errors {r2[variant]['errors']} of {len(at_te)} "
              f"(by k: {r2[variant]['errors_by_k']}, tests by k: {r2[variant]['tests_by_k']})")
    print(f"   training attempts {len(at_tr)} ({r2['train_accepted']} accepted); evidence of pooled units: "
          + ", ".join(f"{u}: s={c[0]}, f={c[1]}" for u, c in r2["pooled"]["counts"].items()))
    res["R2"] = r2

    print("\nR3. A BRANCHING RELATION: 'down' to either subordinate")
    evb, _ = episodes(1200, TRAIN_P, (1, 2), np.random.default_rng(41), branching=True)
    ok_read = 0; pats = set()
    for e in evb:
        S0, S1 = PERSON[e["before"]], PERSON[e["after"]]
        d = S1 - S0; dplus, dminus = (d > 0).astype(int), (d < 0).astype(int)
        a = int(np.argmax(dminus.sum(axis=1))); target = int(np.argmax(dplus.sum(axis=1)))
        found = None
        i, r = a, 0                                            # 'up' propagator
        while r < KMAX:
            i = REL["up"](i); r += 1
            if i < 0: break
            if i == target: found = ("up", r, ["up"] * r); break
        if found is None:                                      # 'down' propagator: a branching front
            front = [(a, [])]
            for r in range(1, KMAX + 1):
                front = [(REL[b](i), pth + [b]) for i, pth in front for b in ("dl", "dr") if REL[b](i) >= 0]
                hit = [pth for i, pth in front if i == target]
                if hit: found = ("down", r, hit[0]); break
        good = found is not None and found[0] == e["v"] and found[1] == e["k"] and found[2] == e["steps"]
        ok_read += int(good); pats.add(("MOVE", found[0]) if good else ("bad",))
    evt, _ = episodes(800, TEST_P, (1, 2), np.random.default_rng(43), branching=True)
    down = [e for e in evt if e["v"] == "down"]
    err_with = sum(path(e["p"], e["steps"])[-1] != e["dest"] for e in evt)
    def default_dest(e):                                       # no path argument: left-first free path
        occ = e["before"]
        def search(i, k):
            if k == 0: return i
            for b in ("dl", "dr"):
                j = REL[b](i)
                if j >= 0 and occ[j] == 0:
                    r = search(j, k - 1)
                    if r is not None: return r
            return None
        return search(e["p"], e["k"])
    err_without = sum(default_dest(e) != e["dest"] for e in down)
    r3 = dict(moves=len(evb), read_correctly=ok_read, patterns=len(pats), test_moves=len(evt),
              test_down=len(down), errors_with_path=err_with, errors_without_path_on_down=err_without)
    res["R3"] = r3
    print(f"   {len(evb)} moves: relation, extent and path read correctly in {ok_read}; {len(pats)} patterns (up, down)")
    print(f"   execution on {len(evt)} new moves: with the path bound {err_with} errors; without it "
          f"{err_without} errors on the {len(down)} downward moves (left-first default)")

    print("\nR4. CORRESPONDENCE BETWEEN CODES (line world; hand and shelf codes independent)")
    r4 = {}
    for n_col, colours in ((3, (1, 2, 3)), (6, (1, 2, 3, 4, 5, 6))):
        E = cs.play("line", 400, np.random.default_rng(3), colours=colours)
        for norm in (False, True):
            o = correspondence(E, n_col, norm)
            key = f"{n_col}_colours_{'normalised' if norm else 'hebbian'}"
            r4[key] = o
            print(f"   {key:22s}: first occurrences bound {o['first_bound']}/{o['first']}; later occurrences bound "
                  f"{o['later_bound']}/{o['later']}; false bindings {o['false_bound']}/{o['false_tests']}")
    # robustness over hand codebooks (the interference depends on which hand codes share units)
    tot = {"hebbian": [0, 0, 0, 0, []], "normalised": [0, 0, 0, 0, []], "renormalised_each_update": [0, 0, 0, 0, []]}
    E6 = cs.play("line", 400, np.random.default_rng(3), colours=(1, 2, 3, 4, 5, 6))
    for seed in range(100, 120):
        for norm, name in ((False, "hebbian"), (True, "normalised"), ("every_update", "renormalised_each_update")):
            o = correspondence(E6, 6, norm, seed=seed)
            tot[name][0] += o["later_bound"]; tot[name][1] += o["later"]; tot[name][2] += o["false_bound"]
            tot[name][3] += int(o["later_bound"] < o["later"]); tot[name][4] += o["fail_occurrence"]
    r4["six_colours_20_hand_codebooks"] = tot
    for name in ("hebbian", "normalised", "renormalised_each_update"):
        t = tot[name]; occ = t[4]
        print(f"   6 colours, 20 hand codebooks, {name:10s}: later occurrences bound {t[0]}/{t[1]}; false bindings {t[2]}; "
              f"codebooks with failures {t[3]}; failures at occurrence number "
              + (f"{min(occ)}-{max(occ)} (median {int(np.median(occ))})" if occ else "--"))
    res["R4"] = r4

    with open("numbers_relations.json", "w") as f:
        json.dump(res, f, indent=1, default=str)
    print("\nwritten numbers_relations.json")
